name: Get Latest UPMetroSkin
on:
  issues:
    types: [ labeled ]
  workflow_dispatch:

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
    - name: Copycat
      uses: andstor/copycat-action@v4.0.0
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        src_owner: redsigma
        src_repo_name: UPMetroSkin
        src_path: /Unofficial 4.x Patch/Main Files [Install First]/
        dst_path: /metro-for-steam/
        dst_owner: SaltireSoul
        dst_repo_name: SteamMetroSkin
        dst_branch: master
        src_branch: master

    - uses: actions/checkout@master
    - name: issue-closure
      uses: bdougie/close-issues-based-on-label@master
      env:
        LABEL: upstream-commit
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
